apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: {{ .Values.configmap.PersistentVolume.name }}
spec:
  capacity:
    storage: {{ .Values.configmap.PersistentVolume.capacity.storage }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: {{ .Values.appName }}
    volumeAttributes:
      source: {{ .Values.configmap.csi.volumeAttributes.source }}
    nodeStageSecretRef:
      name: {{ .Values.configmap.csi.nodeStageSecretRef.name }}
      namespace: {{ .Values.configmap.csi.nodeStageSecretRef.namespace }}