---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.configmap.persistentVolumeClaim.claimName }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: {{ .Values.configmap.PersistentVolume.name }}
  storageClassName: smb