---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: web-tcp
    port: 32400
    protocol: TCP
    targetPort: 32400
  selector:
    app: {{ .Values.appName }}
  type: LoadBalancer