---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.appName }}-lib-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.configmap.PersistentVolume.capacity.request | default "250Gi" | quote }}
  volumeName: {{ .Values.configmap.PersistentVolume.name | default "smb-pvc" | quote }}
  storageClassName: smb

---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: {{ .Values.appName }}-lib-pv
spec:
  capacity:
    storage: {{ .Values.configmap.PersistentVolume.capacity.storage | default "250Gi" | quote }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: {{ .Values.appName }}
    volumeAttributes:
      source: {{ .Values.configmap.csi.volumeAttributes.source }}
    nodeStageSecretRef:
      name: {{ .Values.configmap.csi.nodeStageSecretRef.name }}
      namespace: {{ .Values.configmap.csi.nodeStageSecretRef.namespace }}