apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.appName }}-postgres
  namespace: {{ .Values.namespace }}
spec:
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.5-v0.3.0@sha256:be3f025d79aa1b747817f478e07e71be43236e14d00d8a9eb3914146245035ba
  instances: 1
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
  managed:
    roles:
      - name: {{ .Values.dbUsername}}
        superuser: true
        login: true
  bootstrap:
    initdb:
      database: {{ .Values.databaseName }}
      owner: {{ .Values.dbUsername }}
      secret:
        name: {{ .Values.appName }}-postgres-user
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;
 
  storage:
    size: 4Gi
    storageClass: local-path